# -*- coding: utf-8 -*-
"""Project (Titan＆Ohtani)of impersonator_plus_plus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXZ6rx3zFDgEO2IbbmASFC6XfY7VYkaH
"""

from google.colab import drive
drive.mount('/content/drive')

# # Install the PyDrive wrapper & import libraries.
# # This only needs to be done once per notebook.
# !pip install -U -q PyDrive
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

# # Authenticate and create the PyDrive client.
# # This only needs to be done once per notebook.
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

"""## Note
Make sure that your runtime type is 'Python 3.6+ with GPU acceleration'. To do so, go to Edit > Notebook settings > Hardware Accelerator > Select "GPU".

# Impersonator++

All Resources:

[![GitHub stars](https://img.shields.io/github/stars/iPERDance/iPERCore?style=social)](https://github.com/iPERDance/iPERCore)

- Paper: https://arxiv.org/pdf/2011.09055.pdf
- Repo: https://github.com/iPERDance/iPERCore
- Project Page: https://www.impersonator.org/work/impersonator-plus-plus.html
- Dataset https://svip-lab.github.io/dataset/iPER_dataset.html
- Forum https://discuss.impersonator.org/
"""

#%%

import IPython
IPython.display.HTML(
   '<h2>Demo</h2><iframe width="75%" height="512" src="https://www.impersonator.org/project_img/impersonator_plus_plus/demo_video/demo_1_512x512.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
)

"""# Dependencies

## System Requirements
 - Linux (test on Ubuntu 16.04 and 18.04) or Windows (test on windows 10)
 - CUDA 10.1, 10.2, or 11.0
 - gcc 7.5+ (needs to support C++14)
 - ffmpeg (ffprobe) 4.3.1+

## Python Requirements
- Python 3.6+
- PyTorch tested on 1.7.0
- Torchvison tested on 0.8.1
- mmcv-full test on 1.2.0
- numpy>=1.19.3
- scipy>=1.5.2
- scikit-image>=0.17.2
- opencv-python>=4.4.0.40
- tensorboardX>=2.1
- tqdm>=4.48.2
- visdom>=0.1.8.9
- easydict>=1.9
- toml>=0.10.2
- git+https://github.com/open-mmlab/mmdetection.git@8179440ec5f75fe95484854af61ce6f6279f3bbc
- git+https://github.com/open-mmlab/mmediting@d4086aaf8a36ae830f1714aad585900d24ad1156
- git+https://github.com/iPERDance/neural_renderer.git@e5f54f71a8941acf372514eb92e289872f272653

# 1. Installation

## 1.1 Instal ffmpeg (ffprobe) and set CUDA_HOME to the system enviroments
"""

# Install ffmpeg (ffprobe)
!apt-get install ffmpeg

# set CUDA_HOME, here we use CUDA 10.1
import os
os.environ["CUDA_HOME"] = "/usr/local/cuda-10.1"

!echo $CUDA_HOME

"""## 1.1 Clone iPERCore Github Repo"""

!git clone https://github.com/iPERDance/iPERCore.git

"""## 1.2 Setup iPERCore"""

cd /content/drive/MyDrive/Project

cp -r /content/drive/MyDrive/Project/pics /content/iPERCore/assets/samples/sources

cp /content/drive/MyDrive/Project/video/Dynamite.mp4 /content/iPERCore/assets/samples/references

cd /content/iPERCore/

!python setup.py develop

"""## 1.3 Download assets
The assets contain all pre-trained models (**checkpoints.zip**), and other executable files (**executables.zip**, this one is only used for Windows. Linux ignores it), such as ffmpeg and ffprobe.

Download links: 
  - checkpoints: https://download.impersonator.org/iper_plus_plus_latest_checkpoints.zip
  - samples: https://download.impersonator.org/iper_plus_plus_latest_samples.zip

You can manually download the **checkpoints.zip**, unzip it, and mv the **checkpoints** (as well as the **samples**) to **assets** folder. 

 Otherwise, you can just run the following scripts to automaticially do these.
"""

# Download all checkpoints
#!wget -O assets/checkpoints.zip "https://1drv.ws/u/s!AjjUqiJZsj8whLkwQyrk3W9_H7MzNA?e=rRje0G"
!wget -O assets/checkpoints.zip "https://download.impersonator.org/iper_plus_plus_latest_checkpoints.zip"
!unzip -o assets/checkpoints.zip -d assets/

!rm assets/checkpoints.zip

# download samples
# !wget -O assets/samples.zip "https://1drv.ws/u/s!AjjUqiJZsj8whLobQPpoxo2hfhURrA?e=EUyIC2"
!wget -O assets/samples.zip  "https://download.impersonator.org/iper_plus_plus_latest_samples.zip"
!unzip -o assets/samples.zip -d  assets
!rm assets/samples.zip

"""# Run Motion Imitation Demo"""

cd /content/iPERCore/

import os
import os.path as osp
import platform
import argparse
import time
import sys
import subprocess
from IPython.display import HTML
from base64 import b64encode, b32encode

"""## Details of Config
 - gpu_ids (str): the gpu_ids, default is "0";
 - image_size (int): the image size, default is 512;
 - num_source (int): the number of source images for Attention, default is 2. Large needs more GPU memory;
 - assets_dir (str): the assets directory. This is very important, and there are the configurations and all pre-trained checkpoints;
 - output_dir (str): the output directory;

 - src_path (str): the source input information. 
       All source paths and it supports multiple paths, uses "|" as the separator between all paths. 
       The format is "src_path_1|src_path_2|src_path_3". 
       
       Each src_input is "path?=path1,name?=name1,bg_path?=bg_path1". 
       
       It must contain 'path'. If 'name' and 'bg_path' are empty, they will be ignored.

       The 'path' could be an image path, a path of a directory contains source images, and a video path.

       The 'name' is the rename of this source input, if it is empty, we will ignore it, and use the filename of the path.

       The 'bg_path' is the actual background path if provided, otherwise we will ignore it.
       
       There are several examples of formated source paths,

        1. "path?=path1,name?=name1,bg_path?=bg_path1|path?=path2,name?=name2,bg_path?=bg_path2",
        this input will be parsed as [{path: path1, name: name1, bg_path:bg_path1},
        {path: path2, name: name2, bg_path: bg_path2}];

        2. "path?=path1,name?=name1|path?=path2,name?=name2", this input will be parsed as
        [{path: path1, name:name1}, {path: path2, name: name2}];

        3. "path?=path1", this input will be parsed as [{path: path1}].

        4. "path1", this will be parsed as [{path: path1}].

 - ref_path (str): the reference input information.
       
       All reference paths. It supports multiple paths, and uses "|" as the separator between all paths.
       The format is "ref_path_1|ref_path_2|ref_path_3".

       Each ref_path is "path?=path1,name?=name1,audio?=audio_path1,fps?=30,pose_fc?=300,cam_fc?=150".

       It must contain 'path', and others could be empty, and they will be ignored.

       The 'path' could be an image path, a path of a directory contains images of a same person, and a video path.

       The 'name' is the rename of this source input, if it is empty, we will ignore it, and use the filename of the path.

       The 'audio' is the audio path, if it is empty, we will ignore it. If the 'path' is a video,
        you can ignore this, and we will firstly extract the audio information of this video (if it has audio channel).

       The 'fps' is fps of the final outputs, if it is empty, we will set it as the default fps 25.

       The 'pose_fc' is the smooth factor of the temporal poses. The smaller of this value, the smoother of the temporal poses. If it is empty, we will set it as the default 300. In the most cases, using the default 300 is enough, and if you find the poses of the outputs are not stable, you can decrease this value. Otherwise, if you find the poses of the outputs are over stable, you can increase this value.

       The 'cam_fc' is the smooth factor of the temporal cameras (locations in the image space). The smaller of this value, the smoother of the locations in sequences. If it is empty, we will set it as the default 150. In the most cases, the default 150 is enough.

       There are several examples of formated reference paths,

        1. "path?=path1,name?=name1,audio?=audio_path1,fps?=30,pose_fc?=300,cam_fc?=150|
            path?=path2,name?=name2,audio?=audio_path2,fps?=25,pose_fc?=450,cam_fc?=200",
            this input will be parsed as
            [{path: path1, name: name1, audio: audio_path1, fps: 30, pose_fc: 300, cam_fc: 150},
             {path: path2, name: name2, audio: audio_path2, fps: 25, pose_fc: 450, cam_fc: 200}]

        2. "path?=path1,name?=name1, pose_fc?=450|path?=path2,name?=name2", this input will be parsed as
        [{path: path1, name: name1, fps: 25, pose_fc: 450, cam_fc: 150},
         {path: path2, name: name2, fps: 25, pose_fc: 300, cam_fc: 150}].

        3. "path?=path1|path?=path2", this input will be parsed as
        [{path: path1, fps:25, pose_fc: 300, cam_fc: 150}, {path: path2, fps: 25, pose_fc: 300, cam_fc: 150}].

        4. "path1|path2", this input will be parsed as
        [{path: path1, fps:25, pose_fc: 300, cam_fc: 150}, {path: path2, fps: 25, pose_fc: 300, cam_fc: 150}].

        5. "path1", this will be parsed as [{path: path1, fps: 25, pose_fc: 300, cam_fc: 150}].

## Run Scripts
"""

# the gpu ids
gpu_ids = "0"

# the image size
image_size = 512

# the default number of source images, it will be updated if the actual number of sources <= num_source
num_source = 2

# the assets directory. This is very important, please download it from `one_drive_url` firstly.
assets_dir = "/content/iPERCore/assets"

# the output directory.
output_dir = "./results"

# the model id of this case. This is a random model name.
model_id = "model_" + str(time.time())

# # This is a specific model name, and it will be used if you do not change it.
# model_id = "axing_1"

# symlink from the actual assets directory to this current directory
work_asserts_dir = os.path.join("./assets")
if not os.path.exists(work_asserts_dir):
    os.symlink(osp.abspath(assets_dir), osp.abspath(work_asserts_dir),
               target_is_directory=(platform.system() == "Windows"))

cfg_path = osp.join(work_asserts_dir, "configs", "deploy.toml")

"""### Run the `trump` case
In this case, there is only a frontal body image as the source inputs.
"""

# # This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
# model_id = "donald_trump_2"

# # the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2\""


# ## the reference input information. There are three reference videos in this case.
# #here \" is escape character of double duote "

# # ref_path = "\"path?=/content/iPERCore/assets/samples/references/akun_1.mp4," \
# #              "name?=akun_2," \
# #              "pose_fc?=300\""

# # ref_path = "\"path?=/content/iPERCore/assets/samples/references/mabaoguo_short.mp4," \
# #              "name?=mabaoguo_short," \
# #              "pose_fc?=400\""

# ref_path = "\"path?=/content/iPERCore/assets/samples/references/akun_1.mp4,"  \
#              "name?=akun_2," \
#              "pose_fc?=300|" \
#              "path?=/content/iPERCore/assets/samples/references/mabaoguo_short.mp4," \
#              "name?=mabaoguo_short," \
#              "pose_fc?=400\""

# print(ref_path)

# !python -m iPERCore.services.run_imitator  \
#   --gpu_ids     $gpu_ids       \
#   --num_source  $num_source    \
#   --image_size  $image_size    \
#   --output_dir  $output_dir    \
#   --model_id    $model_id      \
#   --cfg_path    $cfg_path      \
#   --src_path    $src_path      \
#   --ref_path    $ref_path

# mp4 = open("/content/iPERCore/results/primitives/donald_trump_2/synthesis/imitations/donald_trump_2-akun_2.mp4", "rb").read()
# data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
# HTML(f"""
# <video width="100%" height="100%" controls>
#       <source src="{data_url}" type="video/mp4">
# </video>""")

# mp4 = open("/content/iPERCore/results/primitives/donald_trump_2/synthesis/imitations/donald_trump_2-mabaoguo_short.mp4", "rb").read()
# data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
# HTML(f"""
# <video width="100%" height="100%" controls>
#       <source src="{data_url}" type="video/mp4">
# </video>""")

"""### Run the `axing_1` case
In this case, there are two source images. The one is the frontal image, and the other is the backside image.
"""

# # This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
# model_id = "axing_1"

# # the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/axing_1,name?=axing_1\""


# ## the reference input information. There are three reference videos in this case.
# # here \" is escape character of double duote "
# ref_path = "\"path?=/content/iPERCore/assets/samples/references/bantangzhuyi_1.mp4," \
#              "name?=bantangzhuyi_1," \
#              "pose_fc?=300\""

# print(ref_path)

# !python -m iPERCore.services.run_imitator  \
#   --gpu_ids     $gpu_ids       \
#   --num_source  $num_source    \
#   --image_size  $image_size    \
#   --output_dir  $output_dir    \
#   --model_id    $model_id      \
#   --cfg_path    $cfg_path      \
#   --src_path    $src_path      \
#   --ref_path    $ref_path

# mp4 = open("./results/primitives/axing_1/synthesis/imitations/axing_1-bantangzhuyi_1.mp4", "rb").read()
# data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
# HTML(f"""
# <video width="100%" height="100%" controls>
#       <source src="{data_url}" type="video/mp4">
# </video>""")

"""### Run the `afan_6` case
In this case, there are two source images, as well as a real background image.
"""

# # This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
# model_id = "afan_6=ns=2"

# # the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6=ns=2," \
#              "name?=afan_6=ns=2," \
#              "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""

# ## the reference input information. There are three reference videos in this case.
# # here \" is escape character of double duote "
# ref_path = "\"path?=/content/iPERCore/assets/samples/references/akGexYZug2Q_2.mp4.mp4," \
#              "name?=akGexYZug2Q_2," \
#              "pose_fc?=300\""

# print(ref_path)

# !python -m iPERCore.services.run_imitator  \
#   --gpu_ids     $gpu_ids       \
#   --num_source  $num_source    \
#   --image_size  $image_size    \
#   --output_dir  $output_dir    \
#   --model_id    $model_id      \
#   --cfg_path    $cfg_path      \
#   --src_path    $src_path      \
#   --ref_path    $ref_path

# mp4 = open("/content/iPERCore/results/primitives/afan_6=ns=2/synthesis/imitations/afan_6=ns=2-akGexYZug2Q_2.mp4", "rb").read()
# data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
# HTML(f"""
# <video width="100%" height="100%" controls>
#       <source src="{data_url}" type="video/mp4">
# </video>""")

"""### Run your custom inputs
You can upload your own custom source images, and reference videos with the followings guidelines.

#### Source Guidelines:
 - Try to capture the source images with the same static background without too complex scene structures. If possible, we recommend using the
actual background.
 - The person in the source images holds an A-pose for introducing the most visible textures.
 - It is recommended to capture the source images in an environment without too much contrast in lighting conditions and lock auto-exposure and auto-focus of the camera.

#### Reference Guidelines:
  - Make sure that there is only **one** person in the reference video. Since,currently, our system does not support multiple people tracking. If there are multiple people, you need firstly use other video processing tools to crop the video.
  - Make sure that capture the video with full body person. Half body will result in bad results.
  - Try to capture the video with the static camera lens, and make sure that there is no too much zoom-in, zoom-out, panning, lens swichtings, and camera transitions. If there are multiple lens switchting and camera transitions, you need firstly use other video processing tools to crop the video.
"""

!ffmpeg -i /content/iPERCore/assets/samples/references/Dynamite.mp4 -r 30 /content/iPERCore/assets/samples/references/Dynamite_30.mp4

# This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
model_id = "Titan_" + str(time.time())

# the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6=ns=2," \
#              "name?=afan_6=ns=2," \
#              "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""

# src_path ="\"path?=/content/iPERCore/assets/samples/sources/pics/Titan/mikasa.jpg," \
# "name?=mikasa," \
# "bg_path?=/content/iPERCore/assets/samples/sources/pics/Titan/sk01_070-2.jpg\"" #|" \
# "path?=/content/iPERCore/assets/samples/sources/pics/Titan/livi_3.jfif," \
# "name?=livi," \
# "bg_path?=/content/iPERCore/assets/samples/sources/pics/Titan/sk05_294-2.jpg\"" 

src_path ="\"path?=/content/iPERCore/assets/samples/sources/pics/So2," \
"name?=So2," \
"bg_path?=/content/iPERCore/assets/samples/sources/pics/Titan/sk01_070-2.jpg\""

ref_path = "\"path?=/content/iPERCore/assets/samples/references/Dynamite_30.mp4," \
             "name?=dynamite," \
             "pose_fc?=200," \
             "fps?=60\""



print(ref_path)

!python -m iPERCore.services.run_imitator  \
  --gpu_ids     $gpu_ids       \
  --num_source  $num_source    \
  --image_size  $image_size    \
  --output_dir  $output_dir    \
  --model_id    $model_id      \
  --cfg_path    $cfg_path      \
  --src_path    $src_path      \
  --ref_path    $ref_path

mp4 = open("/content/iPERCore/results/primitives/So2/synthesis/imitations/So2-dynamite.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f"""
<video width="100%" height="100%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")

cp /content/iPERCore/results/primitives/So2/synthesis/imitations/So2-dynamite.mp4 /content/drive/MyDrive/Project/video

# This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
model_id = "Ohtani_" + str(time.time())

# the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6=ns=2," \
#              "name?=afan_6=ns=2," \
#              "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""

src_path = "\"path?=/content/iPERCore/assets/samples/sources/pics/Ohtani/ShoheiOtani.jpg, name?=Ohtani," \
"bg_path?=/content/iPERCore/assets/samples/sources/pics/Titan/sk05_294-2.jpg\""

## the reference input information. There are three reference videos in this case.
# here \" is escape character of double duote "
ref_path = "\"path?=/content/iPERCore/assets/samples/references/akGexYZug2Q_2.mp4.mp4," \
             "name?=akGexYZug2Q_2," \
             "pose_fc?=300\""

# ref_path = "\"Make your own inputs\""

print(ref_path)

!python -m iPERCore.services.run_imitator  \
  --gpu_ids     $gpu_ids       \
  --num_source  $num_source    \
  --image_size  $image_size    \
  --output_dir  $output_dir    \
  --model_id    $model_id      \
  --cfg_path    $cfg_path      \
  --src_path    $src_path      \
  --ref_path    $ref_path

mp4 = open("/content/iPERCore/results/primitives/synthesis/imitations/-akGexYZug2Q_2.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f"""
<video width="100%" height="100%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")

mp4 = open("/content/iPERCore/results/primitives/mikasa/synthesis/imitations/mikasa-dynamite.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f"""
<video width="100%" height="100%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")

"""# Run Novel View Synthesis

## Render Novel View with T-pose
"""

!python demo/novel_view.py --gpu_ids 0 \
   --image_size 512 \
   --num_source 2   \
   --output_dir "./results" \
   --assets_dir "./assets"  \
   --model_id   "afan_6=ns=2" \
   --src_path   "path?=./assets/samples/sources/afan_6/afan_6=ns=2,name?=afan_6=ns=2,bg_path?=./assets/samples/sources/afan_6/IMG_7217.JPG" \
   --T_pose

